In [2]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

# data contoh(ganti dengan data anda)
data = np.array([[2.0, 5.0],
               [1.0, 4.0],
               [3.0, 6.0]])

# Inisialisasi objek minMaxScaler
scaler = MinMaxScaler()

# fit dan transformasi data menggunakan Min-Max Scaling
scaled_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("\nData setelah Min-Max Scalling:")
print(scaled_data)

Data Asli:
[[2. 5.]
 [1. 4.]
 [3. 6.]]

Data setelah Min-Max Scalling:
[[0.5 0.5]
 [0.  0. ]
 [1.  1. ]]


In [3]:
import numpy as np
from sklearn.preprocessing import StandardScaler

data = np.array([[2.0, 5.0],
                [1.0, 4.0],
                [3.0, 60]])

scaler = StandardScaler()

z_score_data = scaler.fit_transform(data)

print("Data Asli:")
print(data)

print("\nData setelah Z-Score Transformation")
print(z_score_data)

Data Asli:
[[ 2.  5.]
 [ 1.  4.]
 [ 3. 60.]]

Data setelah Z-Score Transformation
[[ 0.         -0.68791204]
 [-1.22474487 -0.72612938]
 [ 1.22474487  1.41404142]]


In [10]:
import numpy as np

# data contoh
data = np.array([200, 300, 400, 500, 600])

# Menentukan faktor penggeseran (scaling factor)
# misalnya 1000 untuk mengubah ke rentang 0-1
scaling_factor = 1000

# Melakukan transformasi Decimal Scaling
scaled_data = data / scaling_factor

print("Data Asli:")
print(data)

print("\nData setelah Decimal Scaling:")
print(scaled_data)

Data Asli:
[200 300 400 500 600]

Data setelah Decimal Scaling:
[0.2 0.3 0.4 0.5 0.6]
